### PR TITLE
Typing literals + UserAgent __repr__

### PR DESCRIPTION
**Pull request by novitae**
- I added type hints for strings to display the possible string values when generating an user agent:
   Capture d’écran 2024-10-20 à 13 27 38
- Also added a `__repr__` method on the class to allow it to be displayed easily. We go from:
   Capture d’écran 2024-10-20 à 13 30 00
   To:
   Capture d’écran 2024-10-20 à 13 29 45

### CODE REVIEW

**Comment by iamdual** [comment]
Thanks. Merging.

**Comment by iamdual** [comment]
I think some changes are not working for older versions. Can we do this in the next new releases or should we extend support directly to 3.9?

**Comment by iamdual** [comment]
Workflow tests are currently working for >=3.7. Also, README needs to be updated. Then the changes will be merged back.

**Comment by novitae** [comment]
> Workflow tests are currently working for >=3.7. Also, README needs to be updated. Then the changes will be merged back.

Nice, what changes aren't supported in 3.6 exactly ?

**Comment by iamdual** [comment]
> > Workflow tests are currently working for >=3.7. Also, README needs to be updated. Then the changes will be merged back.
> 
> Nice, what changes aren't supported in 3.6 exactly ?

`typing.Literal` is not supported.

**Pull request merged**
